controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


    # config/routes.yaml
video_consultation:
    path: /video-consultation
    controller: App\Controller\VideoConsultationController::index